### PR TITLE
fix: layout shift bcs of sign in Account modal

### PR DESCRIPTION
**Pull request by Kinfe123**
Layoutshit caused by the Account button modal

### CODE REVIEW

**Comment by jln13x** [comment]
we have a horizontal scrollbar now, wanna fix that? @Kinfe123

**Comment by Kinfe123** [comment]
Sorry .. it was smooth on my pc ..i will take a look at it man!

**Comment by Kinfe123** [comment]
Can you check it now ? .. i guess it is fixed by now :)

**Comment by Kinfe123** [comment]
the issue i guess happens to persist on modal elements causing it a layout shift on landing page but this pr will fix that from happening again

**Comment by jln13x** [comment]
CleanShot 2024-01-22 at 21 33 23@2x

Getting this on mobile viewport now, you aswell?

**Comment by Kinfe123** [comment]
it is been fixed btw check it out

**Pull request merged**
